graph LR
	root[examples]:::root --> 1[example.py]:::file
	root[examples]:::root --> 2[example_diagram.png]:::file

classDef root fill:#fff, stroke-width:0px;
classDef folder fill:#f7ce7f, stroke-width:0px;
classDef file fill:#f2f2f2, stroke-width:0px;